### ISSUE TITLE
przepisac to

### ISSUE THREAD

**Issue by guamencja** [lisqu16/hboard#6]
przepisac to

**Comment by piotrbadelek** [comment]
tak

**Comment by lisqu16** [comment]
btw ja to serio przepisze gdzies za 4 dni

**Comment by guamencja** [comment]
bardzo to przepisałeś, gratulacje

**Comment by ghost** [comment]
> bardzo to przepisałeś, gratulacje

tak

**Comment by guamencja** [comment]
> > bardzo to przepisałeś, gratulacje
> 
> tak

discord to syf nie będę na to gowno pisal bota

**Comment by ghost** [comment]
> > > bardzo to przepisałeś, gratulacje
> > 
> > 
> > tak
> 
> discord to syf nie będę na to gowno pisal bota

no chyba że tak

**Comment by SoGreeno** [comment]
> > > bardzo to przepisałeś, gratulacje
> > 
> > 
> > tak
> 
> discord to syf nie będę na to gowno pisal bota

rigcz

**Comment by ghost** [comment]
teraz każdy kto z siecioradia ma gh już uczestniczył w tym issue xD

**Comment by SoGreeno** [comment]
nice

**Comment by SoGreeno** [comment]
rip. can we get f

**Comment by guamencja** [comment]
> rip. can we get f
> 
> 

F
